### ISSUE TITLE
Duvida Sobre authenticação

### ISSUE THREAD

**Issue by mauroagr** [devaguia/correios-php#17]
Matheus @devaguia ,
Estava olhando o código, e acho que me perdi na analise..kkkk.
Quando eu já tenho o token, ele chama a api dos correios de token novamente no construct do Correios(), certo? Ou entendi errado?
Teoricamente, esta chamada adicional poderia ser 'economizada', e passar o token direto, pois ele que é usado no restante do código?
Pensei bobagem ou entendi errado?
Abraço,
Mauro

**Comment by devaguia** [comment]
Opa. @mauroagr 
Na verdade, se você passar o token no construtor da classe Correios, a requisição de authentication não vai ser feita. Veja:

### Construtor do Correios.php
```PHP
    public function __construct(string $username, string $password, string $postcard, bool $isTestMode = false, string $token = '')
    {
        $this->requestNumber = time();
        $this->postcard      = $postcard;
    
        // Método de autenticação é chamado passando os parametros
        $this->authenticate($username, $password, $postcard, $isTestMode, $token);
    }
```

### Função authenticate no Correios.php
Perceba que eu verifico se um token foi passando por parametro. Se sim, adiciono o token passado, se não, ele gerar um token novo.
```PHP
    private function authenticate(string $username, string $password, string $postcard, bool $isTestMode, string $token): void
    {
        $this->authentication = new Authentication($username, $password, $postcard, $isTestMode);
        // Verifica se o token existe
        if ($token) {
            // Define o token na classe de autenticação e para a execução da função
            $this->authentication->setToken($token);
            return;
        }

        // Gera um novo token caso não passe na verificação
        // Só vai ser executado caso não seja passado um token
        $this->authentication->generateToken();
    }

```

**Comment by mauroagr** [comment]
Eu tinha entendi errado...
Quem faz realmente à chamada à api é o generateToken().
Perfeito...entendido.
