### ISSUE TITLE
Criar novos testes para a propriedade 'objectType' na classe de produto

### ISSUE THREAD

**Issue by devaguia** [devaguia/correios-php#44]
Uma nova funcionalidade foi criada na classe de produto, porem nenhum teste automatizado foi criado para ela. Necessário elaborar novos cenários de testes e aplicá-los para garantir o bom funcionamento do código.

**Comment by sauloraizen** [comment]
Olá, estava testando a biblioteca e quando usa o cálculo do frete informando objectType(2), gera um erro (Ao informar tpObjeto="2", o(s) parâmetro(s) comprimento e largura e altura ou peso cúbico é(são) obrigatório(s).)

Creio que isso acontece por que os parâmetros que vão na requisição estão com nomes errados(width, height, length, diameter), na API dos correios são outros nomes em português.

**Comment by devaguia** [comment]
Bom dia @sauloraizen 

Vou dar uma olhada mais tarde, e te dou um retorno. Obrigado!

**Comment by devaguia** [comment]
Opa @sauloraizen 
Subi um branch com uma correção teste. Poderia testar para mim?

LInk da branch: https://github.com/devaguia/correios-php/tree/object_type

```
$correios->price()->get(
    serviceCodes:['04162'],
    products:[
        [
		'weight' => 300,
		'height' => 200,
		'width' => 200,
		'cubicWeight' => 100,
		'objectType' => 2
	]
    ],
    originCep:'00000000',
    destinyCep:'00000000'
);
```
