### ISSUE TITLE
setLotId opcional

### ISSUE THREAD

**Issue by rafaelstz** [devaguia/correios-php#47]
Quando `setLotId` não está especificado, o request retorna array empty. Colocando o número 1 caso não houver LotId instanciado, ajudaria a reduzir a complexidade de implementação.

<img width="406" alt="Screenshot 2024-08-20 at 7 11 40 PM" src="https://github.com/user-attachments/assets/64763631-39ce-4a4f-8c21-79a49ced662f">

**Comment by devaguia** [comment]
@rafaelstz Na classe principal do projeto eu adiciono um requestNumber padrão usando a função ```time()```, que vai trazer o timestamp do momento da requisição. Se eu fizesse da mesma forma adicionando o 'LT' no final, resolveria para você?

Ex: 
Request Number: 1724275001
Lot ID: 1724275001LT

![Captura de Tela 2024-08-21 às 6 10 59 PM](https://github.com/user-attachments/assets/0b7ac95d-e148-4b09-94d8-deb8dd27097a)

**Comment by rafaelstz** [comment]
sim @devaguia

**Comment by devaguia** [comment]
@rafaelstz Pode testar para mim? Inclusive os métodos de getDr e getContract da classe Authentication, fiz algumas pequenas alterações.

Estão na branch: https://github.com/devaguia/correios-php/tree/changes_1_0_3

**Comment by rafaelstz** [comment]
Hey @devaguia, funcionou e os testes unitários também passaram!

<img width="1106" alt="Screenshot 2024-08-23 at 6 46 59 PM" src="https://github.com/user-attachments/assets/8b11287c-7988-425d-be64-896791ae9f62">

<img width="560" alt="Screenshot 2024-08-23 at 6 47 56 PM" src="https://github.com/user-attachments/assets/1c36fd63-4f35-46aa-ac2e-bf6fa3b6993c">

**Comment by devaguia** [comment]
Show @rafaelstz amanhã jogo pra master e subo a versão nova no packgist

**Comment by rafaelstz** [comment]
@devaguia seria bom incluir esse bugfix na próxima versão também.
https://github.com/devaguia/correios-php/pull/48

**Comment by devaguia** [comment]
@rafaelstz Mandei a att agora, vou verificar e adicionar essa na próxima.
