### ISSUE TITLE
Seguro 

### ISSUE THREAD

**Issue by marceloGreenn** [devaguia/correios-php#51]
Olá boa tarde 
eu gostaria de saber como eu poderia adicionar o seguro no calculo do frete

**Comment by mauroagr** [comment]
Eu faço o seguro manualmente conforme o valor do pedido no retorno da do frete e somo o valor. 
Preciso fazer o calculo, pois como simples nacional, preciso inserir em cima do valor do frete + seguro que vai na NF o valor do imposto que vou pagar, então preciso tratar manualmente igual.

**Comment by marceloGreenn** [comment]
Entendi, ai quando vai gerar a etiqueta vc coloca esse valor que vc calculou manualmente no caso?

**Comment by mauroagr** [comment]
Na verdade, na hora de gerar a etiqueta eu passo o valor declarado, que é o valor do pedido.

**Comment by marceloGreenn** [comment]
show de bola obrigado, vou seguir seus passos

**Comment by devaguia** [comment]
@marceloGreenn Boa tarde. Considera como resolvida a sua dúvida?

Obrigado @mauroagr

**Comment by marceloGreenn** [comment]
sim ta otimo obrigado
