### ISSUE TITLE
Erro de Token

### ISSUE THREAD

**Issue by mauroagr** [devaguia/correios-php#54]
Matheus (@devaguia), 
Começou da erro do nada...tem alguma ideia?

GTW-008: Token não válido para este ambiente.

object(stdClass)#74 (4) { ["msgs"]=> array(1) { [0]=> string(47) "GTW-008: Token não válido para este ambiente." } ["date"]=> string(19) "2024-11-08T12:56:52" ["method"]=> string(4) "POST" ["path"]=> string(18) "/preco/v1/nacional" } 

Obrigado.

**Comment by devaguia** [comment]
Opa @mauroagr. Isso ocorre para todas as rotas ou somente para a rota de 'preço'? Está usando o ambiente de produção ou de testes?

**Comment by devaguia** [comment]
Algum retorno @mauroagr

**Comment by mauroagr** [comment]
Esqueci de finalizar, foi mal @devaguia 
Foi uma cadeia de problemas no sistema. Caiu o script de atualização de token, e ai lascou...com outros problemas.
Não entendi o motivo da mensagem sem aquela, mas ai quando colocava o token na unha, ele rodava. Ou seja, o token vencido tava dando mensagem de token do ambiente errado...
Resolvido

**Comment by devaguia** [comment]
Entendi. Tranquilo! Qualquer coisa estou a disposição.
